name: Build main

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/pip
                      ~/.platformio/.cache
                  key: ${{ runner.os }}-pio
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
            - name: Install ClangFormat
              run: sudo apt-get install -y clang-format
            - name: Install PlatformIO Core
              run: pip install --upgrade platformio
            - name: ClangFormat check
              run: find ./src ./include -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)' -exec clang-format --dry-run -Werror -style=file -i {} \;
            - name: Build PlatformIO Project
              run: |
                pio run -e ILI9488
                pio run -e ST7796
                pio run -e headless
                mv .pio/build/ILI9488/firmware.bin .pio/build/ILI9488/firmware-ILI9488.bin
                mv .pio/build/ST7796/firmware.bin .pio/build/ST7796/firmware-ST7796.bin
                mv .pio/build/headless/firmware.bin .pio/build/headless/firmware-headless.bin
            - name: "Update experimental tag"
              uses: rickstaa/action-create-tag@v1
              with:
                  tag: "experimental"
                  force_push_tag: true
                  message: "Development release"
            - name: Publish release
              uses: "softprops/action-gh-release@v1"
              with:
                  tag_name: "experimental"
                  name: "Development release"
                  body: "Latest successful build of the main branch, use at your own risks"
                  prerelease: true
                  draft: false
                  fail_on_unmatched_files: true
                  files: |
                      .pio/build/ILI9488/firmware-ILI9488.bin
                      .pio/build/ST7796/firmware-ST7796.bin
                      .pio/build/headless/firmware-headless.bin
                      gerber/Gerber_K40-Control-Panel.zip
