name: Build main

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                  path: |
                      ~/.cache/pip
                      ~/.platformio/.cache
                  key: ${{ runner.os }}-pio
            - uses: actions/setup-python@v4
              with:
                  python-version: "3.9"
            - uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'yarn'
            - name: Install ClangFormat
              run: sudo apt-get install -y clang-format
            - name: Install PlatformIO Core
              run: pip install --upgrade platformio
            - name: Install main Node.js dependencies
              run: yarn install --frozen-lockfile
            - name: Install WebUI Node.js dependencies
              working-directory: './webui'
              run: yarn install --frozen-lockfile
            - name: Prettier checks
              run: npx prettier --check ./webui
            - name: ClangFormat check
              run: find ./src ./include -regex '.*\.\(cpp\|hpp\|cu\|c\|h\)' -exec clang-format --dry-run -Werror -style=file -i {} \;
            - name: Build PlatformIO Project
              run: pio run
            - name: Build WebUI
              working-directory: './webui'
              run: yarn build
            - name: Build FS image
              run: pio run --target buildfs
            - name: "Update experimental tag"
              uses: rickstaa/action-create-tag@v1
              with:
                  tag: "experimental"
                  force_push_tag: true
                  message: "Development release"
            - name: Publish release
              uses: "softprops/action-gh-release@v1"
              with:
                  tag_name: "experimental"
                  name: "Development release"
                  body: "Latest successful build of the main branch, use at your own risks"
                  prerelease: true
                  draft: false
                  fail_on_unmatched_files: true
                  files: |
                      .pio/build/nodemcu-32s/spiffs.bin
                      .pio/build/nodemcu-32s/firmware.bin
                      gerber/Gerber_K40-Control-Panel.zip
