#ifndef UI_DISPLAY_H
#define UI_DISPLAY_H

#define DISPLAY_SCREEN_WIDTH 480
#define DISPLAY_SCREEN_HEIGHT 320

#define DISPLAY_DRIVER_ST7796 0
#define DISPLAY_DRIVER_ILI9488 1

#ifndef DISPLAY_DRIVER
#define DISPLAY_DRIVER DISPLAY_DRIVER_ST7796
#endif

#endif
